apiVersion: v1
kind: Service
metadata:
  name: Transfertregistry
spec:
  type: NodePort
  selector:
    app: registry
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30500
  sessionAffinity: None

#Dcp faut se connecter avec docker login Transfertregistry:30500 -u cyberoot -p cyberoot
#ce sont les identifiant qu'on avaisdonner sur la config htpasswd

#Potentiel problematiques:
# 1- coreDns resoud pas Transfertregistry : faut simplement l'ajouter sur le etc/hoste de chaque node
# 2- probleme de certificat tls : faut ajouter les certificats sur /usr/local/share/ca-certificates de chaque node et update les certifs